wantedRows = {0  : "marketCap", 
              1  : "enterpriseValue",
              2  : "trailingPe",
              3  : "forwardPe",
              4  : "5YrPeg",
              5  : "priceSales",
              6  : "priceBook",
              7  : "evSales",
              8  : "evEBITDA",
              39 : "profitMargin",
              40 : "operatingMargin",
              41 : "returnOnAssets",
              42 : "returnOnEquity",
              43 : "revenue",
              44 : "revenuePerShare",
              45 : "quarterlyRevenueGrowth",
              46 : "grossProfit",
              47 : "EBITDA",
              48 : "netIncomeForCommon",
              49 : "Diluted EPS",
              50 : "quarterlyEarningsGrowth",
              51 : "totalCash",
              52 : "cashPerShare",
              53 : "totalDebt",
              54 : "debtEquity",
              55 : "currentRatio",
              56 : "bookValuePerShare", 
              57 : "operatingCashFlow",
              58 : "leveredFreeCashFlow",
              9 : "beta5YrMonthly",
              10 : "52WeekChange",
              11 : "spy52WeekChange",
              12 : "52WeekHigh",
              13 : "52WeekLow",
              14 : "50dayMvAvg",
              15 : "200dayMvAvg",
              16 : "avg3MonthVol",
              17 : "avg10DayVol",
              18 : "sharesOutstanding",
              19 : "sharesFloating",
              20 : "heldByInsiders",
              21 : "heldByInstitutions",
              22 : "sharesShort1MonthPrior",
              23 : "shortRatio",
              24 : "shortToFloat",
              25 : "shortToOutstanding",
              26 : "sharesShort2MonthsPrior",
              27 : "forwardDividendRate",
              28 : "forwardDividendYield",
              29 : "trailingDividendRate",
              30 : "trailingDividendYield",
              31 : "5yrAvgDividendYield",
              32 : "payoutRatio",
              33 : "dividendDate",
              34 : "exDividendDate",
              35 : "lastSplitFactorNewPerOld",
              36 : "lastSplitDate",
              60 : "currentPrice",}

letterNumbers = ["marketCap", 
                 "enterpriseValue",
                 "revenue",
                 "grossProfit",
                 "EBITDA",
                 "netIncomeForCommon",
                 "totalCash",
                 "totalDebt",
                 "operatingCashFlow",
                 "leveredFreeCashFlow",
                 "avg3MonthVol",
                 "avg10DayVol",
                 "sharesOutstanding",
                 "sharesFloating",
                 "sharesShort1MonthPrior",
                 "sharesShort2MonthsPrior",]

percentageNumbers = ["profitMargin",
                     "operatingMargin",
                     "returnOnAssets",
                     "returnOnEquity",
                     "quarterlyRevenueGrowth",
                     "quarterlyEarningsGrowth",
                     "52WeekChange",
                     "spy52WeekChange",
                     "heldByInsiders",
                     "heldByInstitutions",
                     "shortToFloat",
                     "shortToOutstanding",
                     "forwardDividendYield",
                     "trailingDividendYield",
                     "payoutRatio",]

dates = ["exDividendDate", 
         "lastSplitDate",]